### PR TITLE
Upgrade React Native version

### PR DESCRIPTION
**Pull request by azimgd**
upgraded via: https://react-native-community.github.io/upgrade-helper/?from=0.68.2&to=0.70.4

tested:
- npm install
- pod install
- npm run ios
- npm run android

### CODE REVIEW

**Comment by azimgd** [comment]
Ready to be reviewed @parasharrajat

**Comment by parasharrajat** [comment]
Thanks. I will check it in sometime. Is it also adding support for turbo modules.

**Comment by azimgd** [comment]
nope, as turbo modules is not a requirement yet

**Comment by azimgd** [comment]
I will create a PR in the future, once e/App has full support for that

**Comment by parasharrajat** [comment]
Ok, the code look straightforward. BTW, Have you tested it on M1 or intel?

**Comment by azimgd** [comment]
m1

**Review by parasharrajat — APPROVED** [review]
LGTM.

cc: @luacmartins

**Review by luacmartins — APPROVED** [review]

**Pull request merged**
