### PR TITLE
Refactor shortcut handler on iOS

### PR DESCRIPTION
**Pull request by azimgd**
Rewriting ios implementation which *apparently* was using private API.

Following PR is relying on https://developer.apple.com/documentation/uikit/uikeycommand

### CODE REVIEW

**Comment by azimgd** [comment]
@parasharrajat @luacmartins ready for review.

**Comment by azimgd** [comment]
@parasharrajat @luacmartins ready to be reviewed. npm version is changed to `1.0.0`

**Comment by azimgd** [comment]
@parasharrajat What's the ETA?

**Review by luacmartins — APPROVED** [review]
Code LGTM. I'll defer to @parasharrajat for testing.

**Comment by azimgd** [comment]
@parasharrajat how much time would you need for tests? Personally tested both physical and simulator version.

**Comment by azimgd** [comment]
You mean building from your xCode and test on the real iPhone right? You have to have a signing certificate and a provisioning profile for that.

**Comment by azimgd** [comment]
That should work, yeap. Just letting you know that you can test multi-key shortcuts on simulator as well.
Make sure to enable “send keyboard input to device” under “I/O - Input” when simulator is running.

**Comment by luacmartins** [comment]
Published the new version to bpm

**Pull request merged**
